export const GET_USERS = 'GET_USERS'
export const GET_USER_BY_ID = 'GET_USER_BYid'
export const CREATE_USER = 'CREATE_USER'
export const UPDATE_USER_BY_ID = 'UPDATE_USER_BYid'
export const DELETE_USER_BY_ID = 'DELETE_USER_BYid'


export const ADMIN_LOGIN = 'ADMIN_LOGIN'
export const ADMIN_LOGIN_INITIAL_DATA = 'ADMIN_LOGIN_INITIAL_DATA'
export const FROGET_PASSWORD_SENT_MAIL = 'FROGET_PASSWORD_SENT_MAIL'
export const FROGET_PASSWORD_SET_NEW_PASSWORD = 'FROGET_PASSWORD_SET_NEW_PASSWORD'


export const DEPT_SUBMIT = 'DEPT_SUBMIT'
export const DEPT_GET = 'DEPT_GET'
export const DEPT_GET_CLONE='DEPT_GET_CLONE'
export const DELETE_DEPT_BY_ID = 'DELETE_DEPT_BY_ID'
export const DEPT_EDIT = 'DEPT_EDIT'
export const DEPT_GET_SINGLE ='DEPT_GET_SINGLE'


export const GET_DEPT_PARENTS_CHILD ='GET_DEPT_PARENTS_CHILD'
export const DEPT_MAP_SUBMIT = 'DEPT_MAP_SUBMIT'
export const GET_DEPT_MAP_DATA = 'GET_DEPT_MAP_DATA'
export const GET_MAP_SINGLE_DATA = 'GET_MAP_SINGLE_DATA'
export const DEPT_MAP_UPDATE = 'DEPT_MAP_UPDATE'
export const DELETE_DEPTMAP_BY_ID ='DELETE_DEPTMAP_BY_ID'


export const EMP_ROL_SUBMIT = 'EMP_ROL_SUBMIT'
export const GET_EMP_ROL_DATA = 'GET_EMP_ROL_DATA'
export const DELETE_EMP_ROL_BY_ID = 'DELETE_EMP_ROL_BY_ID'
export const EMP_ROL_UPDATE = 'EMP_ROL_UPDATE'


export const GET_ALL_EMP_ROLE='GET_ALL_EMP_ROLE'
export const GET_ALL_DEPENDENT_DEPT_LEVEL='GET_ALL_DEPENDENT_DEPT_LEVEL'

export const CHILD_REPORT_WITH_TRANSACTION_LIST='CHILD_REPORT_WITH_TRANSACTION_LIST'
export const MASTER_REPORT_LIST='MASTER_REPORT_LIST'

export const CHILD_REPORT_WITH_TRANSACTION_LIST_CLONE='CHILD_REPORT_WITH_TRANSACTION_LIST_CLONE'
export const MASTER_REPORT_LIST_CLONE='MASTER_REPORT_LIST_CLONE'

export const ALL_ADMINS_WITH_REPORT='ALL_ADMINS_WITH_REPORT'


export const CHILD_REPORT_WITH_TRANSACTION_LIST_USER='CHILD_REPORT_WITH_TRANSACTION_LIST_USER'
export const MASTER_REPORT_LIST_USER='MASTER_REPORT_LIST_USER'

export const CHILD_REPORT_WITH_TRANSACTION_LIST_CLONE_USER='CHILD_REPORT_WITH_TRANSACTION_LIST_CLONE_USER'
export const MASTER_REPORT_LIST_CLONE_USER='MASTER_REPORT_LIST_CLONE_USER'